spring.application.name=backend

server.port=9001

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=artify
spring.datasource.password=infreeJ

# mybatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=io.github.infreeJ.backend.**

# 나노바나나 API
#gemini.api.key=AIzaSyCNd3x-WgZxrzQqcoRFMZ4dS6rYmKbyq8A
#gemini.api.key=AIzaSyAOH03KXuB18P4zYCZ6YthcBv60UVJ1Hdw
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image-preview
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0:generateImages

#gemini.api.key=YOUR_API_KEY_OR_OAUTH_TOKEN
#gemini.project.id=Artify
#gemini.location=global

gemini.project.id=artify-473206
gemini.location=global
gemini.service-account.path=C:/dev/personal-project/artify-473206-2db131a2c129.json

