spring.application.name=backend

server.port=9001

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=artify
spring.datasource.password=infreeJ

# mybatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=io.github.infreeJ.backend.**

# Gemini API 설정
gemini.api.project-id=artify-v2
#gemini.api.location=us-central1
gemini.api.location=us-east4